import { SectionIntro } from '../../../Kinetic'

const blocks = [
  {
    number: '01',
    title: 'KPI & Goal Tracking',
    body: [
      'Reporting should begin with what your business is trying to achieve.',
      'We define the relevant KPIs around your actual objectives rather than using the same metric list for every account.',
    ],
    listLabel: 'Depending on the goal, this may include',
    list: [
      'Reach and impressions',
      'Engagement',
      'Engagement rate',
      'Audience growth',
      'Video views and watch metrics',
      'Saves and shares',
      'Profile activity',
      'Link clicks',
      'Website sessions from social',
      'Leads and inquiries',
      'Ecommerce actions',
      'Campaign performance',
      'Community response metrics',
    ],
    note: 'Where conversion tracking is available, we connect relevant social activity with downstream business actions.',
  },
  {
    number: '02',
    title: 'Cross-Platform Performance Reporting',
    body: [
      'Businesses rarely operate on one social platform.',
      'We consolidate relevant performance data from platforms such as Facebook, Instagram, LinkedIn, TikTok, and YouTube.',
    ],
    extra: [
      'The report provides a consistent structure while preserving platform-specific context. We do not treat every platform metric as directly interchangeable.',
    ],
    note: 'Different platforms use different definitions, audiences, content formats, and distribution systems. The objective is to create a coherent business view without creating misleading comparisons.',
  },
  {
    number: '03',
    title: 'Audience & Growth Analysis',
    body: [
      'Audience growth is useful only when you understand what is changing behind the number.',
      'We can review the following where platform data allows.',
    ],
    listLabel: 'We can review',
    list: [
      'Follower or subscriber growth',
      'Growth trends over time',
      'Audience composition where available',
      'Audience location and demographic information where available',
      'Audience activity patterns',
      'Significant growth or decline periods',
      'Relationship between audience growth and engagement',
      'Changes in audience response',
    ],
    note: 'We also look for unusual patterns that may require further investigation rather than assuming every increase represents meaningful growth.',
  },
  {
    number: '04',
    title: 'Content Performance Analysis',
    body: [
      'Knowing the average performance of thirty posts is useful.',
      'Knowing which five posts created the strongest response is often more useful. We analyze performance across relevant content dimensions.',
    ],
    listLabel: 'We analyze',
    list: [
      'Top-performing content',
      'Underperforming content',
      'Content formats',
      'Content pillars',
      'Topics and themes',
      'Hooks and messaging',
      'Video performance',
      'Carousel performance',
      'Promotional content',
      'Educational content',
      'Brand content',
      'Publishing patterns',
    ],
    note: 'Where sufficient historical data exists, we can identify recurring patterns that help shape future content planning.',
  },
  {
    number: '05',
    title: 'Campaign Performance Analysis',
    body: [
      'Individual campaigns should be evaluated separately from general account performance.',
      'We can analyze relevant campaign periods to understand the following.',
    ],
    listLabel: 'We can analyze',
    list: [
      'Campaign reach',
      'Engagement',
      'Content response',
      'Audience response',
      'Traffic',
      'Lead activity',
      'Ecommerce actions',
      'Top-performing campaign content',
      'Underperforming campaign elements',
      'Campaign learnings',
    ],
    note: 'Where tracking is available, campaign performance can also be connected with website or conversion activity.',
  },
  {
    number: '06',
    title: 'Organic vs Paid Performance',
    body: [
      'Organic and paid social activity should not always be evaluated using the same framework.',
      'Where paid campaign data is available, we can separate relevant organic and paid performance to help you understand the following.',
    ],
    listLabel: 'We can separate',
    list: [
      'Organic content performance',
      'Paid campaign performance',
      'Reach generated by each',
      'Engagement differences',
      'Traffic contribution',
      'Lead or conversion activity',
      'Content that performs well organically',
      'Content that performs differently when promoted',
    ],
    note: 'The goal is to understand the contribution of each activity rather than treating all social results as one number.',
  },
  {
    number: '07',
    title: 'Community & Reputation Metrics',
    body: [
      'Social performance also includes what happens after someone interacts with your content.',
      'Where relevant data is available, reporting can include the following.',
    ],
    listLabel: 'Reporting can include',
    list: [
      'Comment volume',
      'Message volume',
      'Response time',
      'Review activity',
      'Review trends',
      'Community feedback',
      'Sentiment themes',
      'Recurring customer questions',
      'Escalated issues',
    ],
    note: 'These insights can also inform community management, customer experience, and future content planning.',
  },
  {
    number: '08',
    title: 'Website, Lead & Conversion Analysis',
    body: [
      'Social media performance should not always stop at the platform.',
      'Where the required tracking is available, we can review relevant downstream activity such as the following.',
    ],
    listLabel: 'We can review',
    list: [
      'Website visits from social',
      'Landing-page sessions',
      'Link clicks',
      'Lead submissions',
      'Contact actions',
      'Ecommerce activity',
      'Product-page visits',
      'Other tracked conversion actions',
    ],
    note: 'Attribution has limitations, especially across platforms and devices. We therefore distinguish between tracked data and inferred contribution rather than presenting every conversion as directly caused by social media.',
  },
  {
    number: '09',
    title: 'Competitive & Industry Benchmarking',
    body: [
      'Performance needs context.',
      'Where reliable data is available, we can provide competitive or category-level context around areas such as the following.',
    ],
    listLabel: 'We can provide context around',
    list: [
      'Content themes',
      'Publishing patterns',
      'Visible engagement patterns',
      'Content formats',
      'Campaign activity',
      'Audience positioning',
      'Industry trends',
    ],
    note: 'Competitor benchmarking is not presented as an exact comparison when underlying platform data is unavailable. The purpose is to identify opportunities and useful patterns, not manufacture precision.',
  },
  {
    number: '10',
    title: 'Strategic Recommendations & Forward Planning',
    body: [
      'A report should not end with “Here are your numbers.”',
      'It should answer “What should we do differently next?”',
    ],
    listLabel: 'Our recommendations can cover',
    list: [
      'Content priorities',
      'Format changes',
      'Topic opportunities',
      'Publishing adjustments',
      'Campaign improvements',
      'Audience opportunities',
      'Community improvements',
      'Platform priorities',
      'Testing opportunities',
      'Content to repeat',
      'Content to reduce or rethink',
    ],
    note: 'Where Framecipher also manages your content or social media, these insights can feed directly into the next planning cycle.',
  },
]

export default function Offerings() {
  return (
    <section className="border-t-2 border-frame-border bg-frame-bg px-4 py-20 md:px-8 md:py-28">
      <div className="mx-auto max-w-[95vw]">
        <SectionIntro
          eyebrow="Capabilities &amp; scope"
          title="What Our Monthly Reporting &amp; Analytics Service Includes"
        >
          Our reporting combines cross-platform data, content analysis, audience insights, campaign
          performance, and strategic recommendations.
        </SectionIntro>

        <div className="grid gap-px border-2 border-frame-border bg-frame-border lg:grid-cols-2">
          {blocks.map((block) => (
            <article key={block.number} className="flex flex-col justify-between bg-frame-bg p-7 md:p-8">
              <div>
                <span className="font-heading text-4xl font-bold leading-none tracking-tighter text-frame-muted">
                  {block.number}
                </span>
                <h3 className="mt-5 font-heading text-lg font-bold uppercase leading-tight tracking-tight text-frame-fg md:text-xl">
                  {block.title}
                </h3>
                {block.body.map((paragraph) => (
                  <p
                    key={paragraph}
                    className="mt-4 text-sm font-medium leading-relaxed text-frame-muted-fg md:text-base"
                  >
                    {paragraph}
                  </p>
                ))}
                {block.extra &&
                  block.extra.map((paragraph) => (
                    <p
                      key={paragraph}
                      className="mt-4 text-sm font-medium leading-relaxed text-frame-muted-fg md:text-base"
                    >
                      {paragraph}
                    </p>
                  ))}
              </div>

              {block.list && (
                <div className="mt-6 border-t-2 border-frame-border/60 pt-4">
                  <span className="text-[10px] font-black uppercase tracking-[0.2em] text-frame-accent">
                    {block.listLabel}
                  </span>
                  <ul className="mt-3 flex flex-wrap gap-2">
                    {block.list.map((entry) => (
                      <li
                        key={entry}
                        className="border border-frame-border bg-frame-muted/10 px-2.5 py-1 text-[11px] font-semibold text-frame-fg"
                      >
                        {entry}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {block.note && (
                <p className="mt-4 border-l-2 border-frame-accent bg-frame-muted/10 p-3 text-xs font-medium leading-relaxed text-frame-muted-fg">
                  {block.note}
                </p>
              )}
            </article>
          ))}
        </div>
      </div>
    </section>
  )
}
