export { default as AboutHero } from './AboutHero'
export { default as AboutOrigin } from './AboutOrigin'
export { default as AboutFounders } from './AboutFounders'
export { default as AboutCapabilityMix } from './AboutCapabilityMix'
export { default as AboutPrinciples } from './AboutPrinciples'
export { default as AboutIndustries } from './AboutIndustries'
export { default as AboutCTA } from './AboutCTA'
