// Specific service page components (Doc Service Experience)
export { default as ServiceExperienceHero } from './ServiceExperienceHero'
export { default as ServiceExperiencePillarServices } from './ServiceExperiencePillarServices'
export { default as ServiceExperienceOfferings } from './ServiceExperienceOfferings'
export { default as ServiceExperienceBusinessCase } from './ServiceExperienceBusinessCase'
export { default as ServiceExperienceProcess } from './ServiceExperienceProcess'
export { default as ServiceExperiencePricing } from './ServiceExperiencePricing'
export { default as ServiceExperienceDetails } from './ServiceExperienceDetails'
export { default as ServiceExperienceFAQ } from './ServiceExperienceFAQ'
export { default as ServiceExperienceRelated } from './ServiceExperienceRelated'
export { default as ServiceExperienceCTA } from './ServiceExperienceCTA'

// Legacy service detail components
export { default as ServiceDetailHero } from './ServiceDetailHero'
export { default as ServiceDetailProblemSection } from './ServiceDetailProblemSection'
export { default as ServiceDetailScopeSection } from './ServiceDetailScopeSection'
export { default as ServiceDetailDeliverablesSection } from './ServiceDetailDeliverablesSection'
export { default as ServiceDetailProcessSection } from './ServiceDetailProcessSection'
export { default as ServiceDetailOutputsSection } from './ServiceDetailOutputsSection'
export { default as ServiceDetailLocalRelevanceSection } from './ServiceDetailLocalRelevanceSection'
export { default as ServiceDetailRelatedWorkSection } from './ServiceDetailRelatedWorkSection'
export { default as ServiceDetailFAQSection } from './ServiceDetailFAQSection'
